//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friends.
        /// </summary>
        public static string btAddFriend {
            get {
                return ResourceManager.GetString("btAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block list.
        /// </summary>
        public static string btBlockLists {
            get {
                return ResourceManager.GetString("btBlockLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block User.
        /// </summary>
        public static string btBlockUser {
            get {
                return ResourceManager.GetString("btBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy code.
        /// </summary>
        public static string btCopyCode {
            get {
                return ResourceManager.GetString("btCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Lobby.
        /// </summary>
        public static string btCreateLobby {
            get {
                return ResourceManager.GetString("btCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string btDelete {
            get {
                return ResourceManager.GetString("btDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend List.
        /// </summary>
        public static string btFriendList {
            get {
                return ResourceManager.GetString("btFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string btFriendRequest {
            get {
                return ResourceManager.GetString("btFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btFriends {
            get {
                return ResourceManager.GetString("btFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go Back.
        /// </summary>
        public static string btGoBack {
            get {
                return ResourceManager.GetString("btGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I&apos;m Ready.
        /// </summary>
        public static string btImReady {
            get {
                return ResourceManager.GetString("btImReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Friend.
        /// </summary>
        public static string btInviteFriend {
            get {
                return ResourceManager.GetString("btInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Lobby.
        /// </summary>
        public static string btJoinLobby {
            get {
                return ResourceManager.GetString("btJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick.
        /// </summary>
        public static string btKick {
            get {
                return ResourceManager.GetString("btKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave Lobby.
        /// </summary>
        public static string btLeaveLobby {
            get {
                return ResourceManager.GetString("btLeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string btLogOut {
            get {
                return ResourceManager.GetString("btLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play As Guest.
        /// </summary>
        public static string btPlayAsGuest {
            get {
                return ResourceManager.GetString("btPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string btStartGame {
            get {
                return ResourceManager.GetString("btStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string btStats {
            get {
                return ResourceManager.GetString("btStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string cbLanguage {
            get {
                return ResourceManager.GetString("cbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalEmail {
            get {
                return ResourceManager.GetString("globalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string globalLogin {
            get {
                return ResourceManager.GetString("globalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalPassword {
            get {
                return ResourceManager.GetString("globalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string globalRegister {
            get {
                return ResourceManager.GetString("globalRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been registered successfully!.
        /// </summary>
        public static string lbAccountRegistered {
            get {
                return ResourceManager.GetString("lbAccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to log in.
        /// </summary>
        public static string lbClickHereLogin {
            get {
                return ResourceManager.GetString("lbClickHereLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you haven&apos;t recieved your message, click here.
        /// </summary>
        public static string lbClickHereResend {
            get {
                return ResourceManager.GetString("lbClickHereResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code has been sent to your email, please type it here:.
        /// </summary>
        public static string lbCodeSent {
            get {
                return ResourceManager.GetString("lbCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string lbEnglish {
            get {
                return ResourceManager.GetString("lbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be the same.
        /// </summary>
        public static string lbErrDiferentPassword {
            get {
                return ResourceManager.GetString("lbErrDiferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is invalid or already exists.
        /// </summary>
        public static string lbErrEmailInvalid {
            get {
                return ResourceManager.GetString("lbErrEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must type something to send a message.
        /// </summary>
        public static string lbErrEmptyMessage {
            get {
                return ResourceManager.GetString("lbErrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect code.
        /// </summary>
        public static string lbErrIncorrectCode {
            get {
                return ResourceManager.GetString("lbErrIncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your message contains invalid characters, only alphanumeric!.
        /// </summary>
        public static string lbErrInvalidMessage {
            get {
                return ResourceManager.GetString("lbErrInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your message is too long, 300 characters max.
        /// </summary>
        public static string lbErrMessageTooLong {
            get {
                return ResourceManager.GetString("lbErrMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops, we couldn&apos;t reach our server, check your conection or try again later!.
        /// </summary>
        public static string lbErrNoConection {
            get {
                return ResourceManager.GetString("lbErrNoConection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops!, our database is not working, try again later!.
        /// </summary>
        public static string lbErrNoDataBase {
            get {
                return ResourceManager.GetString("lbErrNoDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops!, Looks like you have no friends :(.
        /// </summary>
        public static string lbErrNoFriends {
            get {
                return ResourceManager.GetString("lbErrNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username Already Exists.
        /// </summary>
        public static string lbErrUsernameExists {
            get {
                return ResourceManager.GetString("lbErrUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is invalid.
        /// </summary>
        public static string lbErrUsernameInvalid {
            get {
                return ResourceManager.GetString("lbErrUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must have a number and a special character.
        /// </summary>
        public static string lbErrWeakPassword {
            get {
                return ResourceManager.GetString("lbErrWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect user or password.
        /// </summary>
        public static string lbErrWrongLogin {
            get {
                return ResourceManager.GetString("lbErrWrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Paswword?.
        /// </summary>
        public static string lbForgotPassword {
            get {
                return ResourceManager.GetString("lbForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string lbLobby {
            get {
                return ResourceManager.GetString("lbLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Friends.
        /// </summary>
        public static string lbManageFriends {
            get {
                return ResourceManager.GetString("lbManageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Ready.
        /// </summary>
        public static string lbNotReady {
            get {
                return ResourceManager.GetString("lbNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string lbOffline {
            get {
                return ResourceManager.GetString("lbOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string lbOnline {
            get {
                return ResourceManager.GetString("lbOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string lbOptions {
            get {
                return ResourceManager.GetString("lbOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string lbPlayers {
            get {
                return ResourceManager.GetString("lbPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready!.
        /// </summary>
        public static string lbReady {
            get {
                return ResourceManager.GetString("lbReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string lbSpanish {
            get {
                return ResourceManager.GetString("lbSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Profile.
        /// </summary>
        public static string lbViewProfile {
            get {
                return ResourceManager.GetString("lbViewProfile", resourceCulture);
            }
        }
    }
}
