//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friends.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block List.
        /// </summary>
        public static string btnBlockLists {
            get {
                return ResourceManager.GetString("btnBlockLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block User.
        /// </summary>
        public static string btnBlockUser {
            get {
                return ResourceManager.GetString("btnBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string btnChange {
            get {
                return ResourceManager.GetString("btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Code.
        /// </summary>
        public static string btnCopyCode {
            get {
                return ResourceManager.GetString("btnCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Lobby.
        /// </summary>
        public static string btnCreateLobby {
            get {
                return ResourceManager.GetString("btnCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark Mode.
        /// </summary>
        public static string btnDarkMode {
            get {
                return ResourceManager.GetString("btnDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deny.
        /// </summary>
        public static string btnDeny {
            get {
                return ResourceManager.GetString("btnDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend List.
        /// </summary>
        public static string btnFriendList {
            get {
                return ResourceManager.GetString("btnFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string btnFriendRequest {
            get {
                return ResourceManager.GetString("btnFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go Back.
        /// </summary>
        public static string btnGoBack {
            get {
                return ResourceManager.GetString("btnGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I&apos;m Ready.
        /// </summary>
        public static string btnImReady {
            get {
                return ResourceManager.GetString("btnImReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Friend.
        /// </summary>
        public static string btnInviteFriend {
            get {
                return ResourceManager.GetString("btnInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string btnJoin {
            get {
                return ResourceManager.GetString("btnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Lobby.
        /// </summary>
        public static string btnJoinLobby {
            get {
                return ResourceManager.GetString("btnJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick.
        /// </summary>
        public static string btnKick {
            get {
                return ResourceManager.GetString("btnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave lobby.
        /// </summary>
        public static string btnLeaveLobby {
            get {
                return ResourceManager.GetString("btnLeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light Mode.
        /// </summary>
        public static string btnLightMode {
            get {
                return ResourceManager.GetString("btnLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok!.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play As Guest.
        /// </summary>
        public static string btnPlayAsGuest {
            get {
                return ResourceManager.GetString("btnPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play As Guest.
        /// </summary>
        public static string btnPlayAsGuest1 {
            get {
                return ResourceManager.GetString("btnPlayAsGuest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Friend Request.
        /// </summary>
        public static string btnSendFriendRequest {
            get {
                return ResourceManager.GetString("btnSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string btnStats {
            get {
                return ResourceManager.GetString("btnStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unblock.
        /// </summary>
        public static string btnUnblock {
            get {
                return ResourceManager.GetString("btnUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        public static string btnVerify {
            get {
                return ResourceManager.GetString("btnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string cmbLanguage {
            get {
                return ResourceManager.GetString("cmbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalsEmail {
            get {
                return ResourceManager.GetString("globalsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string globalsLogin {
            get {
                return ResourceManager.GetString("globalsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalsPassword {
            get {
                return ResourceManager.GetString("globalsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string globalsRegister {
            get {
                return ResourceManager.GetString("globalsRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalsUsername {
            get {
                return ResourceManager.GetString("globalsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been registered successfully!.
        /// </summary>
        public static string lblAccountRegistered {
            get {
                return ResourceManager.GetString("lblAccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anihilated Babies: .
        /// </summary>
        public static string lblAnihilatedBabies {
            get {
                return ResourceManager.GetString("lblAnihilatedBabies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked Users.
        /// </summary>
        public static string lblBlockedUsers {
            get {
                return ResourceManager.GetString("lblBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string lblChange {
            get {
                return ResourceManager.GetString("lblChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed successfully!!.
        /// </summary>
        public static string lblChangePasswordSucces {
            get {
                return ResourceManager.GetString("lblChangePasswordSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your profile.
        /// </summary>
        public static string lblChangeProfile {
            get {
                return ResourceManager.GetString("lblChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your profile picture.
        /// </summary>
        public static string lblChosepfp {
            get {
                return ResourceManager.GetString("lblChosepfp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to continue.
        /// </summary>
        public static string lblClickHereContinue {
            get {
                return ResourceManager.GetString("lblClickHereContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLick here to log in.
        /// </summary>
        public static string lblClickHereLogin {
            get {
                return ResourceManager.GetString("lblClickHereLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you haven&apos;t recieved your message, click here.
        /// </summary>
        public static string lblClickHereResend {
            get {
                return ResourceManager.GetString("lblClickHereResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code has been sent to your email, please type it here:.
        /// </summary>
        public static string lblCodeSent {
            get {
                return ResourceManager.GetString("lblCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confrim Password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string lblCurrentPassword {
            get {
                return ResourceManager.GetString("lblCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your lobby code: .
        /// </summary>
        public static string lblEnterCode {
            get {
                return ResourceManager.GetString("lblEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paswords must be the same.
        /// </summary>
        public static string lblErrDiferentPassword {
            get {
                return ResourceManager.GetString("lblErrDiferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is invalid or already exists.
        /// </summary>
        public static string lblErrEmailInvalid {
            get {
                return ResourceManager.GetString("lblErrEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must type something to send a message.
        /// </summary>
        public static string lblErrEmptyMessage {
            get {
                return ResourceManager.GetString("lblErrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect code.
        /// </summary>
        public static string lblErrIncorrectCode {
            get {
                return ResourceManager.GetString("lblErrIncorrectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Email is invalid or already exists.
        /// </summary>
        public static string lblErrInvalidEmail {
            get {
                return ResourceManager.GetString("lblErrInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your message contains invalid characters, only alphanumeric.
        /// </summary>
        public static string lblErrInvalidMessage {
            get {
                return ResourceManager.GetString("lblErrInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This lobby doesn&apos;t exist, try again!.
        /// </summary>
        public static string lblErrLobbyNotFound {
            get {
                return ResourceManager.GetString("lblErrLobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your message is too long, 300 characters max.
        /// </summary>
        public static string lblErrMessageTooLong {
            get {
                return ResourceManager.GetString("lblErrMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You haven&apos;t blocked anyone yet!.
        /// </summary>
        public static string lblErrNoBlockedUsers {
            get {
                return ResourceManager.GetString("lblErrNoBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops, we couldn&apos;t reach our server, check your conection or try again later!.
        /// </summary>
        public static string lblErrNoConection {
            get {
                return ResourceManager.GetString("lblErrNoConection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops!, our database is not working, try again later!.
        /// </summary>
        public static string lblErrNoDataBase {
            get {
                return ResourceManager.GetString("lblErrNoDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! looks like you have no friend requests :(.
        /// </summary>
        public static string lblErrNoFriendRequests {
            get {
                return ResourceManager.GetString("lblErrNoFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! looks like you have no friends :(.
        /// </summary>
        public static string lblErrNoFriends {
            get {
                return ResourceManager.GetString("lblErrNoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Looks like you haven&apos;t played any game, go play! .
        /// </summary>
        public static string lblErrNoStats {
            get {
                return ResourceManager.GetString("lblErrNoStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username already exists.
        /// </summary>
        public static string lblErrUsernameExists {
            get {
                return ResourceManager.GetString("lblErrUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username is invalid.
        /// </summary>
        public static string lblErrUsernameInvalid {
            get {
                return ResourceManager.GetString("lblErrUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found, try again later.
        /// </summary>
        public static string lblErrUserNotFound {
            get {
                return ResourceManager.GetString("lblErrUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must have a number and a special character.
        /// </summary>
        public static string lblErrWeakPassword {
            get {
                return ResourceManager.GetString("lblErrWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect username or password.
        /// </summary>
        public static string lblErrWrongLogin {
            get {
                return ResourceManager.GetString("lblErrWrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find User.
        /// </summary>
        public static string lblFindUser {
            get {
                return ResourceManager.GetString("lblFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password?.
        /// </summary>
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string lblLobby {
            get {
                return ResourceManager.GetString("lblLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Friends.
        /// </summary>
        public static string lblManageFriends {
            get {
                return ResourceManager.GetString("lblManageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monsters Created: .
        /// </summary>
        public static string lblMonstersCreated {
            get {
                return ResourceManager.GetString("lblMonstersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Username.
        /// </summary>
        public static string lblNewUsername {
            get {
                return ResourceManager.GetString("lblNewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Ready.
        /// </summary>
        public static string lblNotReady {
            get {
                return ResourceManager.GetString("lblNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string lblOffline {
            get {
                return ResourceManager.GetString("lblOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string lblOnline {
            get {
                return ResourceManager.GetString("lblOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string lblOptions {
            get {
                return ResourceManager.GetString("lblOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string lblPlayers {
            get {
                return ResourceManager.GetString("lblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready!.
        /// </summary>
        public static string lblReady {
            get {
                return ResourceManager.GetString("lblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string lblSpanish {
            get {
                return ResourceManager.GetString("lblSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed successfully!.
        /// </summary>
        public static string lblSuccesPassword {
            get {
                return ResourceManager.GetString("lblSuccesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User ID.
        /// </summary>
        public static string lblUserId {
            get {
                return ResourceManager.GetString("lblUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ViewProfile.
        /// </summary>
        public static string lblViewProfile {
            get {
                return ResourceManager.GetString("lblViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume.
        /// </summary>
        public static string lblVolume {
            get {
                return ResourceManager.GetString("lblVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins: .
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your email to verify it&apos;s you.
        /// </summary>
        public static string lblWriteEmail {
            get {
                return ResourceManager.GetString("lblWriteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Stats!.
        /// </summary>
        public static string lblYourStats {
            get {
                return ResourceManager.GetString("lblYourStats", resourceCulture);
            }
        }
    }
}
